<?php

namespace App\Exports;

use Maatwebsite\Excel\Concerns\FromArray;
use Maatwebsite\Excel\Concerns\WithHeadings;

class DiagnosticosExport implements FromArray, WithHeadings
{
    protected $diagnosticos;

    public function __construct($diagnosticos)
    {
        $this->diagnosticos = $diagnosticos;
    }

    public function array(): array
    {
        $data = [];

        foreach ($this->diagnosticos as $d) {
            $data[] = [
                $d->id,
                $d->nombre_entidad,
                $d->orden_entidad,
                $d->sector_publico,
                $d->nombre_responsable,
                $d->cargo_responsable,
                $d->correo_responsable,
                $d->tiene_area_ia ? 'Sí' : 'No',
                $d->num_funcionarios_ti,
                $d->presupuesto_anual_ti,
                $d->tiene_centro_servidores_propio,
                $d->usa_nube,
                $d->modelo_tecnologico_predominante,
                $d->modelo_tecnologico_otros,
                $d->recursos_tecnologicos_descripcion,
                $d->recursos_tecnologicos_archivo,
                $d->dispone_gpu,
                implode('; ', $d->tecnologias_gestion ?? []),
                $d->tecnologias_gestion_otros,
                implode('; ', $d->herramientas_bigdata ?? []),
                $d->herramientas_bigdata_otros,
                implode('; ', $d->arquitectura_almacenamiento ?? []),
                $d->arquitectura_almacenamiento_otros,
                implode('; ', $d->sistemas_analisis_ia ?? []),
                $d->sistemas_analisis_ia_otros,
                $d->mecanismos_respaldo_continuidad,
                $d->indicadores_rendimiento_infraestructura,
                $d->conoce_marco_interoperabilidad,
                $d->usa_lcii,
                $d->datos_estandarizados,
                $d->usa_xroad,
                $d->usa_scd,
                $d->etapa_uso_ia,
                $d->politica_gobierno_datos,
                $d->proyectos_ia_ejecucion,
                $d->num_proyectos_ia,
                implode('; ', $d->tipos_aplicaciones_ia ?? []),
                $d->tipos_aplicaciones_ia_otros,
                $d->soluciones_ia_proyectadas,
                $d->cancelo_proyectos_ia_por_infra,
                $d->tiene_laboratorios_alianzas_ia ? 'Sí' : 'No',
                $d->participa_redes_innovacion ? 'Sí' : 'No',
                $d->proyectos_cofinanciados ? 'Sí' : 'No',
                $d->volumen_datos_esperado,
                $d->frecuencia_procesamiento,
                $d->frecuencia_procesamiento_otra,
                $d->estimacion_capacidad_gpu,
                $d->estimacion_cpu_ram,
                $d->estimacion_almacenamiento,
                $d->requiere_almacenamiento_alta_velocidad ? 'Sí' : 'No',
                $d->requiere_bases_datos_especiales ? 'Sí' : 'No',
                $d->nivel_velocidad_respuesta,
                $d->sla_disponibilidad_esperado,
                $d->requiere_autoescalado ? 'Sí' : 'No',
                $d->crecimiento_demanda_esperado,
                $d->prioridad_gpu,
                $d->prioridad_almacenamiento,
                $d->prioridad_conectividad,
                $d->prioridad_talento,
                $d->prioridad_herramientas,
                $d->necesidades_integracion,
                $d->requerimientos_seguridad,
                $d->restricciones_nube,
                $d->inversion_proyectada,
                $d->likert_infraestructura_suficiente,
                $d->likert_presupuesto_adecuado,
                $d->likert_contratacion_facilita,
                $d->likert_personal_suficiente,
                $d->likert_marco_regulatorio_favorece_nube,
                $d->likert_soberania_datos_obstaculo,
                $d->likert_gobernanza_datos_clara,
                $d->likert_conectividad_adecuada,
                $d->likert_ciberseguridad_suficiente,
                $d->likert_falta_interoperabilidad_limita,
                $d->conoce_lineamientos_mspi_ia,
                $d->analisis_riesgos_ia_especifico,
                $d->clasificacion_datos_mspi,
                $d->barreras_tecnologicas,
                $d->barreras_normativas,
                $d->barreras_organizacionales,
                $d->barreras_financieras,
                $d->dificultades_interoperabilidad_xroad,
                $d->elementos_prioritarios_habilitar,
                $d->casos_exito,
                $d->observaciones_adicionales,
                $d->created_at,
            ];
        }

        return $data;
    }

    public function headings(): array
    {
        return [
            'ID',
            'P1 Nombre Entidad',
            'P2 Orden de la Entidad',
            'P3 Sector Público',
            'P4 Nombre del Responsable',
            'P4 Cargo del Responsable',
            'P4 Correo del Responsable',
            'P5 Cuenta con Área de IA/Datos',
            'P6 Número de Funcionarios de TI',
            'P7 Presupuesto Anual de TI (SMMLV)',
            'P8 Centro de Servidores Propio',
            'P9 Usa Nube',
            'P10 Modelo Tecnológico Predominante',
            'P10 Otros (cuál)',
            'P11 Recursos Tecnológicos (descripción)',
            'P11 Archivo Adjunto',
            'P12 Dispone de GPU',
            'P13 Tecnologías de Gestión',
            'P13 Otros (cuál)',
            'P14 Herramientas Big Data',
            'P14 Otros (cuál)',
            'P15 Arquitectura de Almacenamiento',
            'P15 Otros (cuál)',
            'P16 Sistemas de Análisis/IA',
            'P16 Otros (cuál)',
            'P17 Mecanismos de Respaldo/Continuidad',
            'P18 Indicadores de Rendimiento',
            'P19 Conoce Marco de Interoperabilidad',
            'P20 Usa LCII',
            'P21 Datos Estandarizados',
            'P22 Usa X-Road',
            'P23 Usa Servicios Ciudadanos Digitales',
            'P24 Etapa de Uso de IA',
            'P25 Política de Gobierno de Datos',
            'P26 Proyectos de IA en Ejecución',
            'P27 Número de Proyectos de IA',
            'P28 Tipos de Aplicaciones de IA',
            'P28 Otro (cuál)',
            'P29 Soluciones de IA Proyectadas',
            'P30 Canceló Proyectos por Infraestructura',
            'P31 Laboratorios/Alianzas de IA',
            'P32 Participa en Redes de Innovación',
            'P33 Proyectos Cofinanciados',
            'P34 Volumen de Datos Esperado',
            'P35 Frecuencia de Procesamiento',
            'P35 Otra (cuál)',
            'P36 Estimación Capacidad GPU',
            'P37 Estimación CPU/RAM',
            'P38 Estimación de Almacenamiento',
            'P39 Requiere Almacenamiento Alta Velocidad',
            'P40 Requiere Bases de Datos Especiales',
            'P41 Nivel de Velocidad de Respuesta',
            'P42 SLA de Disponibilidad Esperado',
            'P43 Requiere Autoescalado',
            'P44 Crecimiento de Demanda Esperado',
            'P45 Prioridad GPU',
            'P45 Prioridad Almacenamiento',
            'P45 Prioridad Conectividad',
            'P45 Prioridad Talento',
            'P45 Prioridad Herramientas',
            'P46 Necesidades de Integración',
            'P47 Requerimientos de Seguridad',
            'P48 Restricciones para Uso de Nube',
            'P49 Inversión Proyectada (USD)',
            'P50 Infraestructura Suficiente',
            'P51 Presupuesto Adecuado',
            'P52 Contratación Facilita Adquisición',
            'P53 Personal Suficiente',
            'P54 Marco Regulatorio Favorece Nube',
            'P55 Soberanía de Datos es Obstáculo',
            'P56 Gobernanza de Datos Clara',
            'P57 Conectividad Adecuada',
            'P58 Ciberseguridad Suficiente',
            'P59 Falta de Interoperabilidad Limita',
            'P60 Conoce Lineamientos MSPI-IA',
            'P61 Análisis de Riesgos de IA',
            'P62 Clasificación de Datos MSPI',
            'P63 Barreras Tecnológicas',
            'P64 Barreras Normativas',
            'P65 Barreras Organizacionales',
            'P66 Barreras Financieras',
            'P67 Dificultades Interoperabilidad/X-Road',
            'P68 Elementos Prioritarios',
            'P69 Casos de Éxito',
            'P70 Observaciones Adicionales',
            'Fecha de Registro',
        ];
    }
}
